package model;
import java.sql.Timestamp;

public class Payment {
    private int paymentId; // Auto-generated by DB (if applicable)
    private String mode;   // e.g., Credit Card, UPI, NetBanking
    private Timestamp timestamp;
    private double amount;
    private int ticketId;
    // Constructors
    public Payment(String mode, Timestamp timestamp, double amount) {
        this.mode = mode;
        this.timestamp = timestamp;
        this.amount = amount;
    }
    

    // Getters and Setters
    public int getPaymentId() {
        return paymentId;
    }

    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }

    public String getMode() {
        return mode;
    }

    public void setMode(String mode) {
        this.mode = mode;
    }

    public Timestamp getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }
    public int getTicketId() {
        return ticketId;
    }

    public void setTicketId(int ticketId) {
        this.ticketId = ticketId;
    }
}
